2022120817:58
___
Date: 08-12-2022 | 17:58
Tags: #code #java #exception 
mapofcontents:
___
## Java Nested try block
В Java разрешено использование блока **try** внутри другого блока **try**. Он называется вложенным блоком **try**. Каждый оператор, который мы вводим в блок try, контекст этого исключения помещается в [[00 Stack|стек]]. Например, внутренний блок **try** может использоваться для обработки исключения **ArrayIndexOutOfBoundsException**, в то время как внешний блок **try** может обрабатывать исключение **ArithematicException** (деление на ноль).

### Зачем использовать вложенный блок **try** 
Иногда может возникнуть ситуация, когда часть блока может вызвать одну ошибку, а сам блок целиком может вызвать другую ошибку. В таких случаях обработчики исключений должны быть вложенными.

-----
**Zero-Links**  (Внутренние ссылки) Линки - ключевые слова
- [[00 Try-Catch block]]
- [[00 Stack]]
- [[00 Exception Basics]]
- [[ml Java Exceptions]]

------
**Links** (Внешние ссылки)
- [Javatpoint](https://www.javatpoint.com/nested-try-block)
